octue/resources/analysis.py, octue/resources/dataset.py, octue/templates/templates.py, octue/utils/folders.py, tests/test_datafile.py, tests/test_dataset.py, tests/test_loggable.py, tests/test_serialisable.py, tests/test_templates.py
* Use dictionary comprehensions for simpler `dict` construction
* Use generator of `tuple`s rather than `dict` if the pairs are only iterated through (saves memory without losing any function)
* Use mapping of `lambda`s instead of chain of `if`s for field lookup selection
* Simplify `PACKAGED_TEMPLATES` tuple construction using a generator comprehension
* Reduce repeated literals and code
* Use `os.sep` for path part separators
* Narrow assertions in `DataSet` tests
* Remove unused module logger
* Factor out repeated class definitions
* Avoid overriding built-in `dir` function
=> Refactor: Minor changes

octue/templates/template-python-fractal/requirements.txt
This allows the fractal template to work with the libraries installed in twined server. At the moment, our dependencies are coupled between twined server and the app that's running. This is not tolerable, we need to be running the apps in their designated environments so the server can run multiple apps at once. Not a small issue.
See also https://github.com/octue/twined-server/issues/2
=> DEPS Update dependencies of the fractal example to work with twined-server

octue/logging_handlers.py, octue/runner.py, tests/test_cli.py, tests/test_logging_handlers.py
Use `SocketHandler` instead of `HTTPHandler` for remote logging.
* #35
=> Fix: Use socket handler for remote logging

octue/resources/analysis.py, octue/runner.py, octue/templates/template-using-manifests/app.py, setup.py, tests/resources/test_analysis.py, tests/test_runner.py
Prevents imaginary attributes being retrieved from `Analysis`.
=> Prevent imaginary/empty attributes being retrieved from Analysis

.github/workflows/check-version-consistency.yml, .github/workflows/python-ci.yml
=> Devops: Move release version GitHub check into python-ci workflow

docs/source/analysis_objects.rst, docs/source/index.rst, octue/mixins/__init__.py, octue/mixins/hashable.py, octue/mixins/serialisable.py, octue/mixins/taggable.py, octue/resources/analysis.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, setup.py, tests/base.py, tests/mixins/test_hashable.py, tests/mixins/test_serialisable.py, tests/resources/test_analysis.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
I've made the hashes cached properties to avoid recomputing them every time they're accessed.
=> Feature: Add hashes of input and configuration data to Analysis instances

octue/mixins/filterable.py, octue/mixins/taggable.py, octue/resources/tag.py, tests/mixins/test_filterable.py, tests/mixins/test_taggable.py, tests/resources/test_tag.py
=> Refactor: Rename TagGroup to TagSet

octue/mixins/filterable.py, octue/resources/filter_containers.py, tests/mixins/test_filterable.py, tests/resources/test_filter_containers.py
* I don't think there's any need for a `yield` method as you can already yield from both a set and a list and they also already exist in memory so there's no benefit to returning a generator from them. Let me know if I've got the wrong end of the stick here
=> Feature: Add order_by method to filter containers

tests/test_cli.py
=> Fix: Send output of CLI tests to temporary directory

.pre-commit-config.yaml, README.md, docs/requirements.txt
* Fix links to documentation in README
* Remove generic content from README
The main fixes to get the docs working were carried out in the admin interface of ReadTheDocs:
* Untick "Install project" in the advanced settings
* Set the default branch to `main` rather than `master` (since we've renamed our base branch)
I also stopped the building of epub and pdf docs as we're not using them.
=> Fix sphinx documentation

octue/__init__.py, octue/cli.py, octue/logging_handlers.py, octue/runner.py, tests/test_cli.py
* Add a package-level logger
* Add `--show-twined-logs` option to CLI so developers can also see logs from the SDK
* Move `handler` argument from `Runner.run` to `Runner` constructor
* Make log format more human readable
=> Feature: Add option to handle developer logs separately

.github/workflows/python-ci.yml
=> Devops: Allow skipping of CI tests

octue/utils/cloud/storage/client.py, tests/__init__.py
=> Fix: Allow storage emulator to find and use a free port

.github/workflows/python-ci.yml, octue/utils/cloud/emulators.py, tests/__init__.py, tests/resources/communication/google_pub_sub/test_service.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py, tests/utils/cloud/storage/test_client.py
=> Refactor: Remove test bucket envar; factor out test project name

octue/deployment/google/Dockerfile
=> IMP: Move Google Cloud Run Dockerfile into SDK

octue/cloud/storage/client.py, octue/resources/datafile.py, octue/resources/tag.py
The metadata is now stored as e.g.
```
{
'id': 'aebc3128-03df-4a11-82fd-9611591abbc6', 
'timestamp': None, 
'hash_value': 'N7aU4g==', 
'cluster': '0', 
'sequence': '1', 
'tags': '[\n    "blah:shah:nah",\n    "blib",\n    "glib"\n]'
}
```
=> Ensure Google Cloud Storage metadata strings do not appear in quotation marks

octue/resources/tag.py, tests/mixins/test_taggable.py, tests/resources/test_tag.py
=> Feature: Allow tags to have capitals and forward slashes in

octue/cloud/storage/client.py, octue/mixins/hashable.py, octue/resources/datafile.py, octue/utils/time.py, tests/resources/test_datafile.py, tests/utils/test_time.py
=> Allow datetime timestamps for datafiles; use GCS custom time field for Datafile.timestamp

octue/mixins/hashable.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, tests/cloud/pub_sub/test_service.py, tests/mixins/test_hashable.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
=> Remove hash value from Datafile GCS metadata

octue/cloud/storage/client.py, octue/resources/datafile.py
=> Fix: Revert custom time datafile metadata change

octue/resources/datafile.py, tests/resources/test_datafile.py
=> Feature: Namespace custom cloud metadata

octue/mixins/filterable.py, tests/mixins/test_filterable.py
=> Feature: Add more filter types

octue/cloud/storage/client.py, octue/mixins/serialisable.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, octue/utils/encoders.py, tests/cloud/storage/test_client.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
=> Feature: Allow gs:// paths to be used in resources

.github/workflows/update-pull-request.yml, octue/cloud/pub_sub/service.py, octue/cloud/pub_sub/subscription.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_service.py, tests/cloud/pub_sub/test_subscription.py
=> Fix: Ensure Service.wait_for_answer timeout value is respected

setup.py, tests/__init__.py, tests/base.py
=> Ensure tests always receive test result modifier on Windows

docs/source/cloud_storage.rst, docs/source/datafile.rst, octue/resources/datafile.py, octue/resources/dataset.py, setup.py, tests/cloud/pub_sub/test_service.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
=> Fix: Remove disparity between Datafile instantiation methods

octue/cloud/pub_sub/service.py, setup.py, tests/cloud/pub_sub/test_service.py
Use service question UUIDs as analysis IDs to allow log messages for a Google Cloud Run service to be filtered for a given question. Also improve the presentation of error messages forwarded from the responding service to the asking service.
=> Use question UUID as analysis ID

octue/resources/datafile.py, setup.py, tests/resources/test_datafile.py
=> Ensure datafile metadata can be set at instantiation for bare cloud objects

octue/cloud/pub_sub/service.py, setup.py, tests/cloud/pub_sub/test_service.py
Ensure exceptions with multiple arguments of any type are formatted and sent correctly to the asking service by the answering service.
=> Format answerer exceptions properly when sending to asker

octue/cloud/storage/client.py, setup.py, tests/resources/test_dataset.py
=> Ensure crc32c hashing on cloud upload works for binary files

octue/cloud/pub_sub/__init__.py, octue/cloud/pub_sub/logging.py, octue/cloud/pub_sub/service.py, setup.py
Simplify Google Pub/Sub retries and restrict them to transient errors, specifically removing retries for `NotFound` errors (these were triggering many unneeded retries on Google Cloud Run). This also stops the retry schedule being proportional to the timeout for waiting for an answer to a question, which could lead to very long retry schedules for large timeouts (e.g. for questions that involve long analyses).
=> Only retry transient errors in Google Pub/Sub code

octue/cloud/pub_sub/service.py, setup.py, tests/cloud/pub_sub/test_service.py
=> Make OrderedMessageHandler work with no timeout

octue/cloud/pub_sub/service.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_service.py
Allow questions with only an input manifest to be asked (questions with only input values are already allowed).
=> Make input values optional when asking a question

octue/cloud/deployment/google/cloud_run.py, setup.py
Acknowledge Pub/Sub messages received on Google Cloud Run straight away rather than waiting for the analysis to complete first. This avoids triggering the same analysis multiple times (due to Pub/Sub sending the same message multiple times), wasting compute resource, and adding a large amount of noise to the logs.
=> Acknowledge Pub/Sub messages received on Google Cloud Run straight away

octue/cloud/deployment/google/cloud_run.py, setup.py
Reverts octue/octue-sdk-python#221
We've had to revert due to limitations in Google Cloud Run:
* Only instances that haven't returned an HTTP status code yet are counted as active
* Acknowledgement of trigger Pub/Sub messages can only be done by returning a status code
* Threads can be launched so the trigger message can be acknowledged to avoid it being sent again, but the instance will then be treated as idle and killed after around 15 minutes
* Together, this means that acknowledgement of trigger Pub/Sub messages can only be done after all processing has completed
* There is also a 600s maximum acknowledgement deadline, after which the message is sent again, resulting in extra containers being spawned and the same computation being carried out multilple times until the first instance …
=> Revert "Acknowledge Pub/Sub messages received on Google Cloud Run straight away"

octue/utils/processes.py, setup.py, tests/utils/test_processes.py
Add a function that makes it easy to run and capture any `stdout` and `stderr` output of subprocesses. This is useful for child services that forward their logs back to the parent as all output produced by non-python processes can be included.
=> Add function for logging subprocess stdout and stderr

docs/source/datafile.rst, octue/resources/datafile.py, setup.py, tests/resources/test_datafile.py
Improve the `Datafile` interface and allow instantiation with local and cloud paths simultaneously.
=> Allow Datafile instantiation with local and cloud paths simultaneously

.github/workflows/python-ci.yml, .github/workflows/release.yml, .github/workflows/update-pull-request.yml, octue/cloud/storage/client.py, octue/resources/dataset.py, requirements-dev.txt, setup.py, tests/cloud/storage/test_client.py
=> Give cloud scandir option to include subdirectories

octue/resources/manifest.py, setup.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
=> Allow Manifest construction from any serialized cloud dataset

octue/definitions.py, octue/resources/dataset.py, setup.py, tests/resources/test_dataset.py
=> Upload dataset metadata file when getting datasets with no existing metadata file

octue/resources/filter_containers.py, setup.py, tests/resources/test_filter_containers.py
=> Let FilterContainer.one method be used with no filters on empty containers

.pre-commit-config.yaml, octue/cloud/pub_sub/service.py, octue/mixins/serialisable.py, octue/resources/dataset.py, octue/resources/manifest.py, octue/resources/tag.py, octue/utils/encoders.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/mixins/test_serialisable.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
Clarify the interface for serialising `Serialisable` instances. Serialising now clearly means converting instances to a string, while a new `to_primitive` method converts instances to a dictionary of python primitives.
=> Clarify the interface for serialising Serialisable instances

docs/requirements.txt, docs/source/conf.py, setup.py
Ensure bullet points render in docs. The problem may have been one of the things listed in [here](https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file). Note that some Chromium-based browsers still aren't rendering the bullet points, but Safari now is.
=> Ensure bullet points render in docs

octue/cloud/storage/client.py, octue/resources/dataset.py, setup.py, tests/base.py, tests/cloud/storage/test_client.py, tests/resources/test_dataset.py
=> Add option to not show cloud directories as blobs in scandir

tests/templates/test_template_apps.py
- Skip failing child services template test on Windows until we have the resources to investigate why
=> Skip test failing on Windows

octue/resources/analysis.py, setup.py, tests/resources/test_analysis.py
Explicitly define `Analysis` attributes so that code introspection tools can more easily detect their existence. This is useful for developers and general transparency/readability of the class interface.
- Define `Analysis` attributes explicitly in constructor rather than implicitly using a `for` loop and `setattr`
=> Define Analysis attributes explicitly

octue/cloud/deployment/google/cloud_run.py, setup.py, tests/cloud/deployment/google/test_cloud_run.py
- Ensure `MissingServiceID` error is raised when the `SERVICE_ID` environment variable is empty or missing on deployed services
=> Ensure MissingServiceID error is raised when appropriate

octue/cloud/pub_sub/service.py, octue/cloud/pub_sub/topic.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_topic.py, tests/templates/test_template_apps.py
- Retry topic existence check if it initially fails by adding timeout parameter
=> Retry topic existence check if it initially fails

octue/cloud/pub_sub/service.py, octue/cloud/pub_sub/subscription.py, setup.py, tests/cloud/pub_sub/test_subscription.py
- Make subscription retry policy exponential and allow customisation
- Stop deleting question topic when stopping waiting for answer
=> Stop high number of retries of publishing answers when asker has timed out

octue/cloud/credentials.py, setup.py, tests/cloud/test_credentials.py
- Allow getting of Google Cloud credentials as a dictionary
- Increase version number
- Add more tests for GCPCredentialsManager
- Update docstrings
=> Allow getting Google Cloud credentials as a dictionary

.pre-commit-config.yaml, octue/cloud/pub_sub/message_handler.py, octue/cloud/pub_sub/service.py, octue/exceptions.py, octue/resources/analysis.py, octue/runner.py, setup.py, tests/cloud/pub_sub/test_service.py, tests/resources/test_analysis.py, tests/resources/test_child.py
Add the ability for parents to monitor the progress of their children's analyses.
- Add ability to validate (against the schema in `twine.json`) and send monitoring updates from a child to its parent
- Allow parents to provide a callback function that handles monitoring updates for e.g. plotting or other visualisation
- Log receipt of questions in Google Cloud Run
- Use latest conventional commits pre-commit hook
- Rename `Service.parse_question` to `Service._parse_question`
- Rename `Service.send_delivery_acknowledgement_to_asker` to `Service._send_delivery_acknowledgement`
=> Add question monitoring ability

octue/resources/datafile.py, setup.py, tests/resources/test_datafile.py
- Allow datafiles to represent HDF5 files
=> Allow datafiles to represent HDF5 files

.pre-commit-config.yaml, docs/source/datafile.rst, requirements-dev.txt, setup.py
- Make `h5py` dependency optional
- Use working version of `docutils` in `pre-commit-config.yaml`
=> Make `h5py` dependency optional

octue/cloud/pub_sub/service.py, octue/resources/child.py, setup.py
- Allow monitor message handler to be given to Child
=> Allow monitor message handler to be given to Child

octue/resources/dataset.py, setup.py, tests/resources/test_dataset.py
- Allow instantiation of `Dataset`s from a local directory recursively and non-recursively
=> Allow instantiation of Dataset from local directory

octue/resources/dataset.py, setup.py, tests/resources/__init__.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
- Preserve directory structure on dataset cloud upload
=> Preserve directory structure in cloud when uploading datasets

octue/resources/dataset.py, tests/resources/test_dataset.py
- Create cloud path in an OS-agnostice way during dataset cloud upload
- Make test OS-agnostic
=> Create cloud path properly during dataset cloud upload

octue/resources/dataset.py, setup.py
Multi-thread uploads of multiple files from dataset to cloud storage. 
When uploading 100 files, the time taken was:
- 15.5s with the new approach
- 50.9s with the old approach
This is a 3.3x speed up that is likely to increase with the number of files in the dataset and the number of threads available.
- Use `ThreadPool` to upload files from a dataset to the cloud
- Lift 10-worker limit for dataset file downloads
- Ensure datafile paths relative to their dataset are constructed correctly on non-Linux-based OSs
=> Use ThreadPool to speed up uploading files from a dataset

docs/source/logging.rst, octue/__init__.py, octue/cloud/deployment/google/cloud_run.py, octue/essentials/monitor_messages.py, octue/log_handlers.py, octue/resources/analysis.py, octue/runner.py, octue/templates/template-child-services/parent_service/app.py, octue/templates/template-python-fractal/app.py, octue/templates/template-using-manifests/app.py, setup.py, tests/cloud/deployment/google/test_cloud_run.py, tests/cloud/pub_sub/test_service.py, tests/test_log_handlers.py
Ensure the root logger includes the analysis ID in the logging context for the duration of the analysis.
- Swap root log handlers for handlers that include the analysis ID in the logging context for duration of analysis
- Allow easy addition of line number, process name, and thread name to logging context via new environment variables
- Ensure analysis logging includes log messages from any packages or modules used during the analysis
- Ensure the name of the module from which the log message is emitted is correct for log messages emitted during the analysis
- Fix Pub/Sub delivery attempt key error
- Rename `create_formatter` to `create_octue_formatter`
- Update example service ID
=> Fix analysis logging

octue/resources/dataset.py, setup.py, tests/resources/test_dataset.py
- Allow kwargs to be passed to `Dataset.from_local_directory` (in response to [this issue](https://github.com/windpioneers/power-loss/pull/163#discussion_r782973746))
=> Allow kwargs to be passed to Dataset.from_local_directory

.dockerignore, Dockerfile, cloudbuild.yaml, octue/cli.py, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, octue/cloud/deployment/google/dataflow/pipeline.py, octue/cloud/pub_sub/topic.py, setup.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py
When deploying a service to Dataflow, add future automated Dataflow deployment to the build trigger. This removes the need to manually re-deploy a service to Dataflow using `octue-app dataflow deploy` each time the build trigger is run.
- Add Cloud Build step to `DataflowDeployer` to deploy a job to Dataflow
- Stop deploying jobs to Dataflow directly from local machine by default in `DataflowDeployer`
- Add option to `deploy dataflow` CLI command to skip creating and running the build trigger and only deploy the Dataflow job
- Allow `Topic` to be instantiated without a namespace
- Make `BaseDeployer` wait for queued builds instead of raising an error
- Ensure `DataflowDeployer._deploy_streaming_dataflow_job` creates jobs if they don't exist when the `update` parameter is `True`
- Ensure …
=> Add Dataflow deployment to generated build trigger

cloudbuild.yaml, octue/cli.py, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, setup.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py
- Push `octue-sdk-python` image to public Docker Hub repository in `cloudbuild.yaml`
- Use latest `octue-sdk-python` image in generated Cloud Build step in `DataflowDeployer`
- Use the image URI template in `cloudbuild.yaml` file generation instead of a static image name
- Split deploying a Dataflow job from creating and triggering a build trigger in `DataflowDeployer`
- Store required environment variables in dictionary in `BaseDeployer`
=> Fix Dataflow deployment

.github/workflows/release.yml, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, octue/cloud/deployment/google/dataflow/pipeline.py, setup.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py
- Allow service account, machine type, and maximum instances options in `octue.yaml` for Dataflow deployments
- Always use latest `octue-sdk-python` image in `DataflowDeployer`
- Move Cloud-Run-only optional `octue.yaml` file options out of `BaseDeployer` and into `CloudRunDeployer`
- Create pipeline options from a dictionary
- Remove `runner` parameter from `create_streaming_job`
- Tag latest image as `latest` in docker workflow
=> Add extra options to `octue.yaml` for Dataflow deployment

.github/workflows/release.yml
- Ignore codecov upload failure in release workflow
=> Ignore codecov upload failure in release workflow

octue/cli.py, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, setup.py, tests/cloud/deployment/google/cloud_run/test_cloud_run_deployer.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py
Add the ability to provide build secrets in `octue.yaml` to be used as build args in the deployers' docker build step. This allows us to remove manual `cloudbuild.yaml` files from some repositories, reducing manual work and repetition, and increasing deployment resilience.
- Add ability to provide build secrets in `octue.yaml`
- Require services to be specified under services key in `octue.yaml`
- Remove redundant passing of image URI template to deployers
- Rename `worker_machine_type` to `machine_type` in `octue.yaml`
=> Add secrets to octue configuration and put services under services key

octue/cloud/deployment/google/dataflow/pipeline.py, setup.py, tests/cloud/deployment/google/cloud_run/test_cloud_run_deployer.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py
- Disable Dataflow Prime if machine type provided for job
- Test generating Cloud Build config with build secrets
=> Disable Dataflow Prime if machine type specified in octue.yaml

.pre-commit-config.yaml, octue/cloud/deployment/google/dataflow/Dockerfile, requirements-dev.txt, setup.py
**IMPORTANT:** There is 1 breaking change.
- **BREAKING CHANGE:** Make apache-beam an optional dependency under the "dataflow" key
=> Make apache-beam an optional dependency under the "dataflow" key

octue/cloud/pub_sub/logging.py, octue/cloud/pub_sub/service.py, octue/utils/exceptions.py, setup.py, tests/cloud/pub_sub/test_service.py
- Forward error/exception log messages to parent successfully
- Factor out exception serialisation into a function
=> Forward error/exception logs to parent successfully

octue/resources/child.py, setup.py
- Add `allow_local_files` parameter to `Child.ask`
=> Allow `Child` to optionally use local files in input manifest

octue/log_handlers.py, setup.py
- Allow `apply_log_handler` to be applied to a logger instance (this is useful for adding a handler to the logger provided by `multiprocessing.get_logger`)
=> Allow log handler function to be applied to a logger instance

octue/cloud/pub_sub/logging.py, setup.py, tests/cloud/pub_sub/test_logging.py
- Convert non-JSON-serialisable log record args to strings before Pub/Sub log emission
=> Fix JSON serialisation in GooglePubSubHandler

.pre-commit-config.yaml, docs/source/index.rst, docs/source/logging.rst, docs/source/manifest.rst, docs/source/version_history.rst, octue/cloud/storage/client.py, octue/cloud/storage/path.py, octue/resources/analysis.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, setup.py, tests/cloud/storage/test_client.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
Simplify manifest creation and simplify `octue.resources` cloud storage methods by inferring `project_name` from credentials file.
**IMPORTANT:** There is 1 breaking change.
- Allow manifests to be defined by a list of dataset paths
- **BREAKING CHANGE:** Infer `project_name` from credentials file and remove its explicit use as a parameter from the following cloud storage methods:
- `GoogleCloudStorageClient`
- `Analysis.finalise`
- `Datafile`
- `Datafile.to_cloud`
- `Dataset.from_cloud`
- `Dataset.to_cloud`
- `Manifest.from_cloud`
- `Manifest.to_cloud`
- Pull cloud path checking into function
- Explicitly include files as a parameter of `Dataset`
- Add `manifest` documentation page
- Update version history documentation page
- Fix RST document reference on `logging` page
- Use latest …
=> Simplify manifest creation and cloud storage methods

.github/workflows/release.yml, README.md, octue/migrations/manifest.py, octue/resources/manifest.py, octue/templates/template-python-fractal/twine.json, octue/templates/template-using-manifests/data/input/manifest.json, octue/templates/template-using-manifests/twine.json, setup.py, tests/base.py, tests/cloud/pub_sub/test_service.py, tests/resources/test_manifest.py, tests/test_runner.py
Simplify instantiation of manifests by specifying their datasets as a dictionary instead of a list with a separate keys parameter.
**IMPORTANT:** There are 3 breaking changes.
- **BREAKING CHANGE:** Subsume `keys` parameter into `datasets` parameter for `Manifest` instantiation by making `datasets` a dictionary
- **BREAKING CHANGE:** Serialise a manifest's datasets as a dictionary
- **BREAKING CHANGE:** Use latest schema for datasets in manifests
- Use `twined==0.2.0`
- Use correct GitHub workflow badge in `README`
=> Combine keys and datasets in Manifest instantiation

.pre-commit-config.yaml, octue/cloud/storage/client.py, octue/migrations/cloud_storage.py, octue/resources/analysis.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, setup.py, tests/cloud/storage/test_client.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
Shift to only supporting full cloud storage paths (e.g. `gs://my-bucket-name/path/to/file.dat`) rather than separate bucket names and paths within buckets (e.g. `my-bucket-name` and `path/to/file.dat`). This makes interacting with cloud storage clearer, makes it clear which cloud provider the data resides with (e.g. Google), and makes the code more resilient.
**IMPORTANT:** There are 6 breaking changes.
- **BREAKING CHANGES:** Deprecate `bucket_name` and `path_in_bucket` parameters in the cloud methods of
- `Datafile`
- `Dataset`
- `Manifest`
- `GoogleCloudStorageClient`
- `Analysis`
- **BREAKING CHANGE:** Store datasets at the exact cloud path given to `Dataset.to_cloud` instead of adding the dataset's name to the end of the path
- Remove deprecated `project_name` code
=> Deprecate old cloud storage parameters

octue/cloud/credentials.py, setup.py, tests/cloud/test_credentials.py
- Allow for ADCs not containing project IDs
- Merge branch 'main' into fix/default-app-credentials
=> FIX: Allow for ADCs not containing project IDs

octue/migrations/manifest.py, setup.py, tests/resources/test_manifest.py
- Fix migration of old manifest datasets format to new format
- Avoid test leakage
=> Fix migration of old manifest datasets format to new format

tests/templates/test_template_apps.py
Skip the `test_using_manifests` test, which has started failing independently of code changes. See issue #385
- Skip independently failing test
=> Skip independently failing test

.github/workflows/python-ci.yml, .github/workflows/release.yml, octue/cloud/pub_sub/service.py, octue/resources/child.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_service.py
- Allow question UUID to be specified in `Child.ask`
- Show CI package installation logs
- Switch parameter order in `Service.ask`
=> Allow specification of question UUID in child ask method

.github/workflows/build-docker-image.yml, octue/cloud/deployment/google/dataflow/Dockerfile, setup.py, tests/utils/test_processes.py
- Add manual docker image build workflow
- Upgrade to `apache-beam==2.37.0`
- Upgrade Dataflow image to `python3.9`
- Simplify subprocess logging test
=> Upgrade Dataflow image to python3.9

octue/configuration.py, octue/templates/template-child-services/elevation_service/octue.yaml, octue/templates/template-child-services/parent_service/octue.yaml, octue/templates/template-child-services/wind_speed_service/octue.yaml, setup.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployment.py, tests/cloud/deployment/google/test_answer_pub_sub_question.py, tests/test_cli.py
- Use correct `octue.yaml` format when loading service configurations in `octue.configuration`
=> Use correct octue.yaml format in configuration loader

.github/workflows/build-docker-image.yml, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, octue/configuration.py, setup.py
Unify the configuration format in `octue.yaml` files for use as service configuration and for use by the cloud deployers.
- Unify deployer configuration with service configuration
- Warn user if there are unused kwargs in `ServiceConfiguration` or `AppConfiguration`
- Allow choice of branch in `build-docker-image` workflow
=> Unify deployer configuration with service configuration

octue/templates/template-using-manifests/requirements.txt, requirements-dev.txt, setup.py, tests/templates/test_template_apps.py
- Use `dateparser==1.1.1` in template to avoid `regex` package bug
- Re-enable temporarily skipped test
=> Use latest dateparser to avoid regex package bug

octue/cloud/pub_sub/service.py, octue/cloud/pub_sub/subscription.py, octue/exceptions.py, pyproject.toml, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_service.py, tests/cloud/pub_sub/test_subscription.py
- Support push subscriptions for Google Pub/Sub services, allowing answers to be pushed to an HTTP endpoint
- Add `push_endpoint` parameter to `Subscription` constructor
- Add  `is_pull_subscription` and `is_push_subscription` properties to `Subscription`
- Switch to parent/child language in `Service` tests for greater clarity/consistency
=> Support push subscriptions for Pub/Sub services

octue/cloud/pub_sub/service.py, pyproject.toml, tests/cloud/pub_sub/mocks.py
Fixes a typo in a parameter name
=> FIX: Update parameter name to remove typo

octue/cli.py, octue/cloud/deployment/google/answer_pub_sub_question.py, octue/cloud/storage/client.py, octue/cloud/storage/path.py, octue/configuration.py, octue/exceptions.py, octue/resources/analysis.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, octue/runner.py, octue/templates/template-child-services/parent_service/app.py, octue/templates/template-python-fractal/app.py, octue/templates/template-using-manifests/app.py, poetry.lock, pyproject.toml, tests/cloud/deployment/google/test_answer_pub_sub_question.py, tests/cloud/storage/test_client.py, tests/cloud/storage/test_path.py, tests/mocks.py, tests/resources/test_analysis.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py, tests/templates/test_template_apps.py, tests/test_cli.py
Improve the interactions of datafiles with datasets and make output datasets available in the cloud via expiring signed URLs after `Analysis.finalise` has been called.
IMPORTANT: There are 3 breaking changes.
- Add the ability to generate expiring signed URLs for datasets and their datafiles
- Add the ability to instantiate datasets and datafiles from signed URLs instead of cloud paths
- **BREAKING CHANGE:** Re-engineer `Dataset.add` so that datafiles are actually copied/uploaded/downloaded to the dataset when adding them
- **BREAKING CHANGE:** Re-engineer `Analysis.finalise` to:
- Provide signed URLs for uploaded datasets if a cloud path to a directory is provided
- Not support local data persistence
- **BREAKING CHANGE:** Remove redundant concepts of `output_dir` and output manifest …
=> Improve dataset/datafile interaction and make output datasets available after analysis finalisation

ATTRIBUTIONS.md, docs/source/license.rst, octue/cli.py, octue/cloud/pub_sub/message_handler.py, octue/log_handlers.py, octue/runner.py, octue/utils/colour.py, pyproject.toml, tests/cloud/pub_sub/test_service.py, tests/test_cli.py, tests/test_log_handlers.py
Add colour to the SDK's log messages that differentiate the following three things from each other:
- The basic log attributes (e.g. module name and log level)
- The analysis ID
- Log messages from any number of levels of children
- Add service-differentiating colours to logs using the `seaborn` colourblind palette
- Separate analysis ID into its own section in the logs
- Avoid adding `None` as a log handler in `Runner`
- Only allow one `StreamHandler` to be applied to the logger at once in `apply_log_handler`
- Only attempt `DataflowDeployer` import inside `dataflow deploy` CLI command
- Add an `ATTRIBUTION.md` file
=> Add service-differentiating colours to logs

octue/cloud/storage/client.py, octue/resources/datafile.py, pyproject.toml, tests/cloud/pub_sub/test_service.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
This release simplifies the `Datafile` class internals and clarifies its metadata resolution order. Stored metadata will now be used in preference to instantiation metadata unless the `hypothetical` parameter is `True`, allowing the removal of some confusing internal logic from the class.
- If `hypothetical` is not `True` when re-instantiating existing datafiles, always use their stored metadata (from the cloud object or local metadata file)
- Store cloud metadata on `Datafile` instances without the `octue__` namespace prefix in its keys
- Make `Datafile` metadata update methods public so they can be called easily by users
- Make it optional whether to include the SDK version in the output of `Datafile.metadata`
- Return `None` from `GoogleCloudStorageClient.get_metadata` if bucket not …
=> Add Datafile parameter for ignoring stored metadata

octue/runner.py, poetry.lock, pyproject.toml, tests/test_runner.py
- Validate output locations given to `Runner`
- Use `twined=^0.4.1`
=> Validate output location in runner instead of twine

octue/cloud/storage/path.py, octue/exceptions.py, octue/resources/datafile.py, octue/resources/dataset.py, pyproject.toml, tests/resources/test_datafile.py, tests/resources/test_dataset.py
- Add ability to download datafiles from a signed URL without cloud permissions
- Add `Datafile.generate_signed_url` method
- Raise error if trying to modify a URL-based datafile
- Raise error if trying to generate a signed URL for a local datafile or dataset
- Use URI terminology in cloud storage path module
- Test that datafiles and datasets can be downloaded from URLs without cloud permissions
=> Add ability to download datafiles from a signed URL without cloud permissions

octue/resources/datafile.py, octue/resources/dataset.py, pyproject.toml, tests/resources/test_datafile.py, tests/resources/test_dataset.py
Add a single method for updating stored datafile and dataset metadata that deduces whether to update the local or cloud metadata.
- Add `Datafile.update_metadata` method
- Add `Dataset.update_metadata` method
- Rename `update_cloud_metadata` parameter to `update_metadata` in `Datafile` instantiation and raise a deprecation warning if the old parameter name is used
=> Unify metadata update methods

octue/cloud/deployment/google/answer_pub_sub_question.py, octue/cloud/deployment/google/cloud_run/flask_app.py, octue/cloud/pub_sub/message_handler.py, octue/cloud/pub_sub/service.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/utils/metadata.py, pyproject.toml, tests/cloud/deployment/google/cloud_run/test_flask_app.py, tests/cloud/pub_sub/test_service.py
Stop Cloud Run services from running a given question more than once and rely on Pub/Sub retries for connection problems.
- Increase default delivery acknowledgement deadline to 120s
- Acknowledge and drop questions redelivered to Cloud Run services based on their UUIDs
- Remove redundant question retries in `Service` and raise error instead if the delivery acknowledgement deadline is reached
- Factor out saving/updating of local metadata files
- Rename local metadata save function
- Rename `Service.send_exception_to_asker` to `Service.send_exception`
- Use "answer" instead of "response" terminology in `Service`
=> Make Cloud Run services idempotent to questions

octue/mixins/__init__.py, octue/mixins/cloud_pathable.py, octue/resources/datafile.py, octue/resources/dataset.py, pyproject.toml, tests/resources/test_dataset.py
- Allow `Dataset.to_cloud` to infer cloud location
- Use cloud paths for relative paths when possible in `Dataset.to_cloud`
- Factor out cloud properties and methods common to `Dataset` and `Datafile` into new `CloudPathable` mixin
=> Allow `Dataset.to_cloud` to infer cloud location

poetry.lock, pyproject.toml
- Use `twined=^0.5.0`, which removes deprecated support for datasets provided as lists instead of as dictionaries
=> Use `twined=^0.5.0`

.pre-commit-config.yaml, octue/cloud/deployment/google/dataflow/deployer.py, octue/cloud/deployment/google/dataflow/setup.py, octue/resources/analysis.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/manifest.py, octue/utils/metadata.py, pyproject.toml, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py, tests/cloud/pub_sub/test_service.py, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tests/resources/test_manifest.py
Standardise the data resource class parameter orders and method names to provide a more consistent and intuitive interface. Also rename the `octue-app` CLI to `octue`.
**IMPORTANT:** There are 5 breaking changes.
- 💥 **BREAKING CHANGE:** Standardise the parameter order in `Datafile`, `Dataset`, and `Manifest`. The order is now:
- `path` first
- Any other parameters that appear explicitly in the class next
- Any mixin kwargs after that
**How to migrate**
If you're using kwargs to provide parameters to instantiate the above classes, no change is needed. If you're using positional args, you'll need to reorder them or switch to using kwargs:
- `Manifest`: provide the `datasets` argument first
- `Dataset`: provide the arguments in this order, omitting any you're not already using: 
```
path, …
```
=> Make most-used interfaces more consistent and intuitive

octue/cli.py, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, pyproject.toml, tests/cloud/deployment/google/cloud_run/test_cloud_run_deployer.py, tests/cloud/deployment/google/cloud_run/test_cloud_run_deployment.py, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py, tests/test_cli.py
- Use name-based service IDs in deployer by default
=>  Use name-based service IDs in deployer

octue/cloud/pub_sub/service.py, pyproject.toml, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_service.py
- Log a warning if the child and parent SDK versions potentially incompatible
- Forward any errors to do with instantiating `GooglePubSubHandler` in child to parent
=> Log a warning if child and parent SDK versions are potentially incompatible

octue/resources/datafile.py, pyproject.toml, tests/resources/test_datafile.py
- Ensure `Datafile` instances have the correct open mode when the `Datafile.open` context manager is used
=>  Ensure Datafile instances have correct open mode in context manager

octue/cli.py, octue/cloud/deployment/google/answer_pub_sub_question.py, octue/cloud/deployment/google/base_deployer.py, octue/cloud/deployment/google/cloud_run/deployer.py, octue/cloud/deployment/google/dataflow/deployer.py, octue/cloud/pub_sub/service.py, octue/templates/template-child-services/elevation_service/octue.yaml, octue/templates/template-child-services/wind_speed_service/octue.yaml, pyproject.toml, tests/cloud/deployment/google/dataflow/test_dataflow_deployer.py, tests/templates/test_template_apps.py
**IMPORTANT:** There is 1 breaking change.
**Remove `--service-id` option from CLI**
Services should now be given meaningful names for IDs instead of UUIDs. Set the "name" and "organisation" fields in your `octue.yaml` file - the service will then use an ID of `<organisation>/<name>`.
- 💥 **BREAKING CHANGE:** Remove `--service-id` option from CLI
- Name `Service` instances by their given service IDs
=> Remove support for setting service UUIDs via CLI

.pre-commit-config.yaml, docs/requirements.txt, pyproject.toml
- Use `poetry` pre-release `1.2.0b2` in docs requirements to avoid `importlib-metadata` dependency resolution failure
=> Fix poetry/importlib-metadata dependency resolution failure for docs

octue/resources/datafile.py, pyproject.toml
- Except `ImportError` if `h5py` package is missing
=> Avoid h5py ImportError when not using HDF5 files

octue/cloud/pub_sub/service.py, octue/resources/analysis.py, octue/resources/manifest.py, pyproject.toml, tests/cloud/pub_sub/test_service.py, tests/resources/test_dataset.py
Use signed URLs to point to cloud datasets in input manifests when sending them to children for processing. This means the children will always be able to access the input datasets - not just in the special case of the parent and child having access to the same buckets.
- Use signed URLs when sending input manifests to services
- Factor out dataset URL signing to new `Manifest` method
- Simplify service tests' arguments
- Update test method docstring
- Ignore irrelevant files in test
=> Ensure children can always access input datasets 

octue/cloud/pub_sub/service.py, octue/resources/child.py, octue/resources/dataset.py, pyproject.toml, tests/cloud/deployment/google/dataflow/test_dataflow_deployment.py, tests/cloud/pub_sub/mocks.py, tests/resources/test_dataset.py
- Set default question timeout to 1 day
- Allow dataset upload without metadata change
- Cache dataset cloud metadata privately on instance
- Only update dataset cloud metadata if it's changed
- Update dataflow deployment test
=> Miscellaneous improvements

octue/cloud/storage/client.py, octue/cloud/storage/path.py, octue/runner.py, pyproject.toml, tests/cloud/storage/test_client.py, tests/cloud/storage/test_path.py, tests/resources/test_dataset.py
- Give specifics in the error raised when a datafile fails dataset file tag template validation
- Ignore trailing slashes when splitting/parsing cloud paths
- Ensure the `Dataset.name` property works for datasets with a cloud path ending in a forward slash
- Ensure `GoogleCloudStorageClient.scandir` works on the root directory of a bucket
=> Fix bugs in cloud path parsing and improve dataset validation feedback

octue/cloud/pub_sub/service.py, pyproject.toml, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_subscription.py, tests/resources/test_child.py
Lazily load Google Cloud credentials for `Service` and `Child` instances, allowing apps that don't always contact their children in an analysis to work without the credentials available when they don't need them (instead of failing as currently happens).
- Allow `Service` to be instantiated without Google Cloud credentials
=> Allow Service to be instantiated without Google Cloud credentials

.github/workflows/python-ci.yml, .github/workflows/release.yml, octue/cli.py, octue/cloud/emulators/child.py, octue/cloud/pub_sub/message_handler.py, octue/cloud/pub_sub/service.py, octue/runner.py, octue/utils/processes.py, octue/utils/threads.py, pyproject.toml, tests/cloud/emulators/test_child_emulator.py, tests/cloud/pub_sub/test_message_handler.py, tests/cloud/pub_sub/test_service.py, tests/utils/test_threads.py
This release upgrades children to send heartbeats to parents. This allows the parent to know that a child it's asked a question to is still alive and hasn't crashed. In the event of a crash, heartbeats stop being received and the parent aborts the questions, avoiding large waits for nothing.
**IMPORTANT:** There are 2 breaking changes.
- Send heartbeat messages to parents from children
- Raise error in parent if child heartbeats aren't received for too long an interval
- Tell user how to question a service after using `octue start` CLI command
- 💥 **BREAKING CHANGE:** Rename `run_subprocess_and_log_stdout_and_stderr` to `run_logged_subprocess`
- Split thread and process utilities into separate modules
- Remove redundant extra `while` loop in `OrderedMessageHandler`
- Remove redundant …
=> Send heartbeats from children to parents

.pre-commit-config.yaml, README.md, docs/contributing.md, octue/resources/datafile.py, octue/resources/dataset.py, pyproject.toml, tests/resources/test_datafile.py, tests/resources/test_dataset.py, tox.ini
Remove confusing warnings about instantiation metadata vs. stored metadata when instantiating datafiles and datasets. Clarify the resolution order when both instantiation metadata and stored metadata are present.
**IMPORTANT:** There are 2 breaking changes.
- Remove misleading metadata override warnings from `Datafile` and `Dataset`
- Use newer poetry syntax for installing extras
- 💥 **BREAKING CHANGE:** Rename Datafile `hypothetical` parameter to `ignore_stored_metadata`
- 💥 **BREAKING CHANGE:** Rename Dataset `hypothetical` parameter to `ignore_stored_metadata`
- Use latest commit message checker
---
<details>
<summary>💥 <b>Rename Datafile `hypothetical` parameter</b></summary>
Replace `hypothetical` with `ignore_stored_metadata`.
</details>
<details>
<summary>💥 <b>Rename Dataset …
=> Remove metadata warning from datafiles and datasets

.github/workflows/python-ci.yml, .github/workflows/release.yml, .github/workflows/version-compatibility.yml, README.md, docs/source/asking_questions.rst, docs/source/manifest.rst, docs/source/testing_services.rst, docs/source/troubleshooting_services.rst, octue/cloud/deployment/google/cloud_run/Dockerfile-python311, octue/cloud/emulators/child.py, octue/cloud/pub_sub/bigquery.py, octue/resources/child.py, octue/templates/template-child-services/parent_service/app.py, poetry.lock, pyproject.toml, terraform/bigquery.tf, terraform/functions.tf, terraform/main.tf, tests/cloud/deployment/google/cloud_run/test_cloud_run_deployment.py, tests/cloud/emulators/test_child_emulator.py, tests/cloud/pub_sub/test_bigquery.py, tests/cloud/pub_sub/test_service.py, tests/resources/test_child.py, tests/test_cli.py
**IMPORTANT:** There are 2 breaking changes.
- 💥 **BREAKING CHANGE:** Return question UUID from `Child.ask`
- Deserialise manifests from events in `get_event`
- Raise error if no events found when calling `get_events`
- Use correct base image for `python3.11` dockerfile
- Return schema-compliant events and attributes from `get_events`
- Import missing APIs into terraform config
- Deploy version `0.5.0` of event handler cloud function and update event store schema
- Update `actions/setup-python` to version 5
- 💥 **BREAKING CHANGE:** Make `db-dtypes` and `google-cloud-bigquery` optional
- Upgrade `gunicorn` to avoid vulnerability
- Loosen `numpy` dependency
- Test retrieving results from real asynchronous question
- Run tests with `python3.10` (`python3.9` isn't available on `macos-latest` …
=> Improve async event retrieval workflow

.devcontainer/devcontainer.json, .gitignore, .pre-commit-config.yaml, octue/cloud/pub_sub/logging.py, octue/diagnostics.py, octue/essentials/monitor_messages.py, octue/mixins/filterable.py, octue/mixins/hashable.py, octue/resources/datafile.py, octue/resources/dataset.py, octue/resources/service_backends.py, octue/runner.py, octue/templates/template-fractal/fractal/mandelbrot.py, poetry.lock, pyproject.toml, setup.cfg, tests/base.py, tests/cloud/emulators/test_child_emulator.py, tests/cloud/storage/test_client.py, tests/resources/test_datafile.py, tests/resources/test_manifest.py, tests/test_runner.py, tests/utils/test_persistence.py
- Switch from `flake8`, `black`, and `isort` to `ruff`
- Remove old formatters/linters and add `ruff` config
- Apply `ruff` to all files
=> Switch to ruff developer tooling

tests/cloud/events/test_attributes.py
- Skip `test_reset_uuid_and_datetime` tests on Windows
=> Skip `test_reset_uuid_and_datetime` tests on Windows
