octue/octue-sdk-python

octue/mixins/filterable.py, tests/mixins/test_filterable.py
=> Feature: Extend string filters

.github/workflows/python-ci.yml
=> Devops: Fix skip tests commit flag

docs/source/dataset.rst, docs/source/filter_containers.rst
=> Fix documentation links

.github/workflows/release.yml
*Coverage Karma can be earned by disproportionally increasing test coverage in the rest of your contributions.
It's an honesty policy - you keep count of your own.
=> WIP: Allow testing of workflow without creating release branch

.github/workflows/release.yml
*Coverage Karma can be earned by disproportionally increasing test coverage in the rest of your contributions.
It's an honesty policy - you keep count of your own.
=> WIP: Continue inspecting working directory of workflow

.github/workflows/release.yml
=> Fix: Checkout code and fix environment variable in release workflow

octue/resources/datafile.py
=> Refactor: Pull Datafile metadata gathering into method

.github/workflows/python-ci.yml, .github/workflows/release.yml, mkver.conf, setup.py
=> Devops: Add automatic versioning

.github/workflows/release.yml
=> OPS: Move quotation mark to correct place

mkver.conf, setup.py
=> OPS: Disable major version increments while package is in beta

octue/resources/datafile.py, setup.py, tests/resources/test_datafile.py
=> Allow new datafiles to be created in the cloud without a local file existing first

.github/workflows/update-pull-request.yml, .pre-commit-config.yaml, setup.py
=> Use latest conventional commits package for CI/CD workflows

octue/resources/label.py, octue/resources/tag.py, setup.py
=> Fix error messages about uppercase characters in tags and labels

octue/cloud/pub_sub/service.py, octue/resources/datafile.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_service.py, tests/resources/test_dataset.py
*Coverage Karma can be earned by disproportionally increasing test coverage in the rest of your contributions.
It's an honesty policy - you keep count of your own.
=> Allow input manifests referencing local files to be used when asking questions

tests/utils/test_processes.py
=> TST: Update issue link

setup.py, tests/utils/test_processes.py
=> Fix subprocess logging tests

octue/cloud/pub_sub/subscription.py, octue/cloud/storage/client.py, setup.py, tests/cloud/pub_sub/mocks.py, tests/cloud/pub_sub/test_subscription.py
- Improve mocking of subscription creation test
=> Improve mocking of Pub/Sub subscription creation test

octue/cloud/pub_sub/subscription.py, octue/cloud/pub_sub/topic.py, setup.py
- Remove extra field from format string
=> Remove extra field from format string

octue/essentials/monitor_messages.py, setup.py, tests/essentials/test_monitor_messages.py
- Add essential monitor message helpers
=> Add essential monitor message helpers

octue/runner.py, setup.py, tests/test_app_modules/app_class/app.py, tests/test_app_modules/app_module/app.py, tests/test_cli.py, tests/test_runner.py
- Allow apps to be written as a class
=> Allow apps to be written as a class

octue/cloud/pub_sub/logging.py, octue/cloud/pub_sub/message_handler.py, octue/cloud/pub_sub/service.py, setup.py, tests/cloud/pub_sub/test_logging.py, tests/cloud/pub_sub/test_service.py
- Add analysis ID to log messages forwarded from child
=> Add analysis ID to log messages forwarded from child

Dockerfile
- Include apache-beam in main Dockerfile
=> Include apache-beam in main Dockerfile

octue/cloud/deployment/google/answer_pub_sub_question.py, setup.py
=> Set the correct default environment variable name

.github/workflows/build-docker-image.yml, setup.py
- Remove extra quotation mark from tag name
=> Fix docker image workflow

poetry.lock, pyproject.toml
- Add missing `packaging` dependency
=> Add missing `packaging` dependency

octue/resources/dataset.py, pyproject.toml
- Pass `hypothetical` parameter through from `Dataset` to `Datafile`
- Make `hypothetical` a private attribute in `Dataset`
- Make `recursive` a private attribute in `Dataset`
=> Pass `hypothetical` parameter through from Dataset to Datafile

.devcontainer/Dockerfile, Dockerfile, pyproject.toml
- Combine duplicate installations in Docker container
- Use new poetry installation script in Docker containers
=> Use new poetry installation script in Docker containers
